In [1]:
import os 
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
# 加载训练设备

# 我们希望能够在硬件加速器，比如 GPU 上训练我们的模型。可以通过 torch.cuda 来检测 GPU 是否可用。

# 	• 
# 	• 

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu' 


#检测gpu是否可用，不可用使用cpuprint('Using {} device'.format(device)) 
#输出使用设备类型

/home/seugaoms/anaconda3/envs/python36/lib/python3.6/site-packages/torch/cuda/__init__.py:80: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0


In [3]:
import torch

In [4]:
# 创建未初始化的Tensor

x = torch.empty(5,3)
print(x)

tensor([[9.4150e+30, 4.5779e-41, 1.8077e-43],
        [0.0000e+00, 7.3345e+15, 3.0882e-41],
        [2.8891e+30, 4.5779e-41,        nan],
        [4.5779e-41, 1.8314e+25, 6.9768e+22],
        [1.4312e+13, 7.2156e+22, 7.0975e+22]])


In [6]:
# 创建随机初始化的Tensor

x = torch.rand(5,3)
print(x)

tensor([[0.1160, 0.2181, 0.1234],
        [0.3537, 0.1321, 0.4220],
        [0.1240, 0.6058, 0.6392],
        [0.6046, 0.5417, 0.0153],
        [0.0099, 0.5124, 0.5715]])


In [7]:
# 创建全为0的Tensor

x = torch.zeros(5,3,dtype=torch.long)

print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
# 根据数据创建

Tensorx = torch.tensor([5.5,3])

print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# 修改原Tensor为全1的Tensor

x = x.new_ones(5,3,dtype=torch.float64)

print(x)

# 修改数据类型
x = torch.rand_like(x,dtype=torch.float64)

print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.1704, 0.3928, 0.3178],
        [0.4650, 0.9630, 0.0467],
        [0.5747, 0.3669, 0.9907],
        [0.2930, 0.0316, 0.1653],
        [0.2916, 0.4923, 0.2285]], dtype=torch.float64)


In [10]:
# 获取Tensor的形状
print(x.size())
print(x.shape)
# 注意：返回的torch.Size其实就是⼀一个tuple, ⽀支持所有tuple的操作。

torch.Size([5, 3])
torch.Size([5, 3])
